#############################################################################
# Makefile for building: simplefitness
# Generated by qmake (3.1) (Qt 6.7.2)
# Project:  simplefitness.pro
# Template: app
# Command: /usr/lib/qt6/bin/qmake -o Makefile simplefitness.pro -spec linux-g++
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_QUICK_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_QMLINTEGRATION_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -mno-direct-extern-access -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -Wextra -mno-direct-extern-access -D_REENTRANT $(DEFINES)
INCPATH       = -I. -I. -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtQuick -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtQmlModels -I/usr/include/qt6/QtQml -I/usr/include/qt6/QtQmlIntegration -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtCore -I. -I/usr/lib/qt6/mkspecs/linux-g++
QMAKE         = /usr/lib/qt6/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt6/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt6/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = simplefitness1.0.0
DISTDIR = /home/ab/Documents/Projects/simplefitness/.tmp/simplefitness1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/lib -Wl,-rpath-link,/usr/lib
LIBS          = $(SUBLIBS) /usr/lib/libQt6Widgets.so /usr/lib/libQt6Quick.so /usr/lib/libQt6OpenGL.so /usr/lib/libQt6Gui.so /usr/lib/libGLX.so /usr/lib/libOpenGL.so /usr/lib/libQt6Sql.so /usr/lib/libQt6QmlModels.so /usr/lib/libQt6Qml.so /usr/lib/libQt6QmlBuiltins.a /usr/lib/libQt6Network.so /usr/lib/libQt6Core.so -lpthread -lGLX -lOpenGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		quickfit.cpp qrc_resources.cpp \
		moc_quickfit.cpp
OBJECTS       = main.o \
		quickfit.o \
		qrc_resources.o \
		moc_quickfit.o
DIST          = /usr/lib/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/qt6/mkspecs/common/unix.conf \
		/usr/lib/qt6/mkspecs/common/linux.conf \
		/usr/lib/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/qt6/mkspecs/qconfig.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_chartsqml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_chartsqml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core5compat.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core5compat_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_example_icons_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_linguist.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdf.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlbuiltins.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlbuiltins_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcompiler.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmldom_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlintegration.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlls_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlnetwork.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3deffects.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickeffects_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimeline.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_shadertools.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_shadertools_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_tools_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannelquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannelquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/qt6/mkspecs/features/default_post.prf \
		/usr/lib/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/qt6/mkspecs/features/permissions.prf \
		/usr/lib/qt6/mkspecs/features/qt.prf \
		/usr/lib/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/qt6/mkspecs/features/resources.prf \
		/usr/lib/qt6/mkspecs/features/moc.prf \
		/usr/lib/qt6/mkspecs/features/link_ltcg.prf \
		/usr/lib/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt6/mkspecs/features/uic.prf \
		/usr/lib/qt6/mkspecs/features/unix/no_direct_extern_access.prf \
		/usr/lib/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/qt6/mkspecs/features/yacc.prf \
		/usr/lib/qt6/mkspecs/features/lex.prf \
		simplefitness.pro quickfit.h main.cpp \
		quickfit.cpp
QMAKE_TARGET  = simplefitness
DESTDIR       = 
TARGET        = simplefitness


first: all
####### Build rules

simplefitness:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: simplefitness.pro /usr/lib/qt6/mkspecs/linux-g++/qmake.conf /usr/lib/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/qt6/mkspecs/common/unix.conf \
		/usr/lib/qt6/mkspecs/common/linux.conf \
		/usr/lib/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/qt6/mkspecs/qconfig.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_chartsqml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_chartsqml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core5compat.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core5compat_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_example_icons_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_linguist.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdf.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlbuiltins.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlbuiltins_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcompiler.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmldom_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlintegration.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlls_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlnetwork.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3deffects.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickeffects_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimeline.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_shadertools.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_shadertools_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_tools_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannelquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannelquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/qt6/mkspecs/features/default_post.prf \
		/usr/lib/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/qt6/mkspecs/features/permissions.prf \
		/usr/lib/qt6/mkspecs/features/qt.prf \
		/usr/lib/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/qt6/mkspecs/features/resources.prf \
		/usr/lib/qt6/mkspecs/features/moc.prf \
		/usr/lib/qt6/mkspecs/features/link_ltcg.prf \
		/usr/lib/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt6/mkspecs/features/uic.prf \
		/usr/lib/qt6/mkspecs/features/unix/no_direct_extern_access.prf \
		/usr/lib/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/qt6/mkspecs/features/yacc.prf \
		/usr/lib/qt6/mkspecs/features/lex.prf \
		simplefitness.pro \
		resources.qrc \
		/usr/lib/libQt6Widgets.prl \
		/usr/lib/libQt6Quick.prl \
		/usr/lib/libQt6OpenGL.prl \
		/usr/lib/libQt6Gui.prl \
		/usr/lib/libQt6Sql.prl \
		/usr/lib/libQt6QmlModels.prl \
		/usr/lib/libQt6Qml.prl \
		/usr/lib/libQt6Network.prl \
		/usr/lib/libQt6Core.prl
	$(QMAKE) -o Makefile simplefitness.pro -spec linux-g++
/usr/lib/qt6/mkspecs/features/spec_pre.prf:
/usr/lib/qt6/mkspecs/common/unix.conf:
/usr/lib/qt6/mkspecs/common/linux.conf:
/usr/lib/qt6/mkspecs/common/sanitize.conf:
/usr/lib/qt6/mkspecs/common/gcc-base.conf:
/usr/lib/qt6/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt6/mkspecs/common/g++-base.conf:
/usr/lib/qt6/mkspecs/common/g++-unix.conf:
/usr/lib/qt6/mkspecs/qconfig.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_charts_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_chartsqml.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_chartsqml_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_core5compat.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_core5compat_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_example_icons_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_help.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_linguist.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_pdf.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_pdf_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_pdfquick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_pdfquick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_pdfwidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatch_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlbuiltins.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlbuiltins_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcompiler.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmldom_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlintegration.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlintegration_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlls_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlnetwork.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlnetwork_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3d.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3d_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetutils.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3deffects.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3deffects_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dglslparser_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpers.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3diblbaker.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticles.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dutils.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basic.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2material.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2material_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universal.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickeffects_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimeline.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimeline_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_shadertools.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_shadertools_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_svgwidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_svgwidgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_tools_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webchannelquick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webchannelquick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt6/mkspecs/features/qt_functions.prf:
/usr/lib/qt6/mkspecs/features/qt_config.prf:
/usr/lib/qt6/mkspecs/linux-g++/qmake.conf:
/usr/lib/qt6/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/qt6/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt6/mkspecs/features/toolchain.prf:
/usr/lib/qt6/mkspecs/features/default_pre.prf:
/usr/lib/qt6/mkspecs/features/resolve_config.prf:
/usr/lib/qt6/mkspecs/features/default_post.prf:
/usr/lib/qt6/mkspecs/features/warn_on.prf:
/usr/lib/qt6/mkspecs/features/permissions.prf:
/usr/lib/qt6/mkspecs/features/qt.prf:
/usr/lib/qt6/mkspecs/features/resources_functions.prf:
/usr/lib/qt6/mkspecs/features/resources.prf:
/usr/lib/qt6/mkspecs/features/moc.prf:
/usr/lib/qt6/mkspecs/features/link_ltcg.prf:
/usr/lib/qt6/mkspecs/features/unix/opengl.prf:
/usr/lib/qt6/mkspecs/features/uic.prf:
/usr/lib/qt6/mkspecs/features/unix/no_direct_extern_access.prf:
/usr/lib/qt6/mkspecs/features/unix/thread.prf:
/usr/lib/qt6/mkspecs/features/qmake_use.prf:
/usr/lib/qt6/mkspecs/features/file_copies.prf:
/usr/lib/qt6/mkspecs/features/testcase_targets.prf:
/usr/lib/qt6/mkspecs/features/exceptions.prf:
/usr/lib/qt6/mkspecs/features/yacc.prf:
/usr/lib/qt6/mkspecs/features/lex.prf:
simplefitness.pro:
resources.qrc:
/usr/lib/libQt6Widgets.prl:
/usr/lib/libQt6Quick.prl:
/usr/lib/libQt6OpenGL.prl:
/usr/lib/libQt6Gui.prl:
/usr/lib/libQt6Sql.prl:
/usr/lib/libQt6QmlModels.prl:
/usr/lib/libQt6Qml.prl:
/usr/lib/libQt6Network.prl:
/usr/lib/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile simplefitness.pro -spec linux-g++

qmake_all: FORCE


all: Makefile simplefitness

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/qt6/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents quickfit.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp quickfit.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		/usr/lib/qt6/rcc \
		logo.png
	/usr/lib/qt6/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/qt6/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/qt6/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_quickfit.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_quickfit.cpp
moc_quickfit.cpp: quickfit.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/ab/Documents/Projects/simplefitness/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/ab/Documents/Projects/simplefitness -I/home/ab/Documents/Projects/simplefitness -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtQuick -I/usr/include/qt6/QtOpenGL -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtQmlModels -I/usr/include/qt6/QtQml -I/usr/include/qt6/QtQmlIntegration -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtCore -I/usr/include/c++/14.1.1 -I/usr/include/c++/14.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/14.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/14.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/14.1.1/include-fixed -I/usr/include quickfit.h -o moc_quickfit.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp quickfit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

quickfit.o: quickfit.cpp quickfit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o quickfit.o quickfit.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_quickfit.o: moc_quickfit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_quickfit.o moc_quickfit.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

.SUFFIXES:

